# -*- coding: utf-8 -*-
"""empty message

Revision ID: 0ea4dd035a20
Revises: c959111f7ca7
Create Date: 2023-07-29 13:23:58.820953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ea4dd035a20'
down_revision = 'c959111f7ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professionals_task_tracker_id_fkey', 'professionals', type_='foreignkey')
    op.drop_column('professionals', 'task_tracker_id')
    op.add_column('task_trackers', sa.Column('professional_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task_trackers', 'professionals', ['professional_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_trackers', type_='foreignkey')
    op.drop_column('task_trackers', 'professional_id')
    op.add_column('professionals', sa.Column('task_tracker_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('professionals_task_tracker_id_fkey', 'professionals', 'task_trackers', ['task_tracker_id'], ['id'])
    # ### end Alembic commands ###
