"""empty message

Revision ID: 4004f0a75d61
Revises: f3a7e2c165dc
Create Date: 2023-07-27 19:08:40.908873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4004f0a75d61'
down_revision = 'f3a7e2c165dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
