"""empty message

Revision ID: 4b77c1b15e07
Revises: 68554d96875a
Create Date: 2023-07-26 17:37:28.501390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b77c1b15e07'
down_revision = '68554d96875a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('skill_id', sa.Integer(), nullable=False))
    op.add_column('professionals', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.add_column('professionals', sa.Column('task_tracker_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'professionals', 'task_trackers', ['task_tracker_id'], ['id'])
    op.create_foreign_key(None, 'professionals', 'users', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'professionals', 'skills', ['skill_id'], ['id'])
    op.add_column('skills', sa.Column('task_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'skills', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('task_tracker_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'task_trackers', ['task_tracker_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_tracker_id')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_column('skills', 'task_id')
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_column('professionals', 'task_tracker_id')
    op.drop_column('professionals', 'parent_id')
    op.drop_column('professionals', 'skill_id')
    # ### end Alembic commands ###
