# -*- coding: utf-8 -*-
"""empty message

Revision ID: 53817c6797eb
Revises: 5e3135fddf07
Create Date: 2023-07-27 18:41:19.650221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "53817c6797eb"
down_revision = "5e3135fddf07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
