# -*- coding: utf-8 -*-
"""empty message

Revision ID: 53d39f6f43ca
Revises: 8ad3e244b71f
Create Date: 2023-07-29 11:53:29.260185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d39f6f43ca'
down_revision = '8ad3e244b71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
