# -*- coding: utf-8 -*-
"""empty message

Revision ID: 5e3135fddf07
Revises: 880789c0f064
Create Date: 2023-07-27 18:40:31.513157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e3135fddf07"
down_revision = "880789c0f064"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
