"""empty message

Revision ID: 68554d96875a
Revises: aef86d11f899
Create Date: 2023-07-26 16:41:49.078772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68554d96875a'
down_revision = 'aef86d11f899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('skills', 'false')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('false', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('skills', 'name')
    # ### end Alembic commands ###
