"""empty message

Revision ID: 880789c0f064
Revises: ec0f1340f228
Create Date: 2023-07-27 18:02:07.934634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '880789c0f064'
down_revision = 'ec0f1340f228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_skills',
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('professional_id', 'skill_id')
    )
    op.drop_constraint('professionals_skill_id_fkey', 'professionals', type_='foreignkey')
    op.drop_column('professionals', 'skill_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professionals', sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('professionals_skill_id_fkey', 'professionals', 'skills', ['skill_id'], ['id'])
    op.drop_table('professional_skills')
    # ### end Alembic commands ###
