# -*- coding: utf-8 -*-
"""empty message

Revision ID: 8ad3e244b71f
Revises: 14ab6900ab04
Create Date: 2023-07-28 17:55:02.095927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad3e244b71f'
down_revision = '14ab6900ab04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('professional_skills_skill_id_fkey', 'professional_skills', type_='foreignkey')
    op.drop_constraint('professional_skills_professional_id_fkey', 'professional_skills', type_='foreignkey')
    op.create_foreign_key(None, 'professional_skills', 'skills', ['skill_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'professional_skills', 'professionals', ['professional_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_constraint('task_skills_task_id_fkey', 'task_skills', type_='foreignkey')
    op.drop_constraint('task_skills_skill_id_fkey', 'task_skills', type_='foreignkey')
    op.create_foreign_key(None, 'task_skills', 'tasks', ['task_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'task_skills', 'skills', ['skill_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_skills', type_='foreignkey')
    op.drop_constraint(None, 'task_skills', type_='foreignkey')
    op.create_foreign_key('task_skills_skill_id_fkey', 'task_skills', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key('task_skills_task_id_fkey', 'task_skills', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'professional_skills', type_='foreignkey')
    op.drop_constraint(None, 'professional_skills', type_='foreignkey')
    op.create_foreign_key('professional_skills_professional_id_fkey', 'professional_skills', 'professionals', ['professional_id'], ['id'])
    op.create_foreign_key('professional_skills_skill_id_fkey', 'professional_skills', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###
