"""empty message

Revision ID: bd33d16d199e
Revises: f10c538dc88a
Create Date: 2023-07-26 16:07:56.321380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd33d16d199e'
down_revision = 'f10c538dc88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
