"""empty message

Revision ID: beabd682b8ab
Revises: 53817c6797eb
Create Date: 2023-07-27 18:47:25.028150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beabd682b8ab'
down_revision = '53817c6797eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
