# -*- coding: utf-8 -*-
"""empty message

Revision ID: c54cc869ca26
Revises: 0ea4dd035a20
Create Date: 2023-08-01 17:18:16.692109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c54cc869ca26"
down_revision = "0ea4dd035a20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
