# -*- coding: utf-8 -*-
"""empty message

Revision ID: c959111f7ca7
Revises: 53d39f6f43ca
Create Date: 2023-07-29 13:13:54.836964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c959111f7ca7'
down_revision = '53d39f6f43ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
