# -*- coding: utf-8 -*-
"""empty message

Revision ID: ec0f1340f228
Revises: f623704925fd
Create Date: 2023-07-27 17:13:58.783158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ec0f1340f228"
down_revision = "f623704925fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_skills",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "skill_id"),
    )
    op.add_column("skills", sa.Column("task_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "skills", "tasks", ["task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "skills", type_="foreignkey")
    op.drop_column("skills", "task_id")
    op.drop_table("task_skills")
    # ### end Alembic commands ###
