# -*- coding: utf-8 -*-
"""empty message

Revision ID: f3a7e2c165dc
Revises: beabd682b8ab
Create Date: 2023-07-27 18:49:53.920745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3a7e2c165dc"
down_revision = "beabd682b8ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
